---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
spec:
  type: ClusterIP
  selector:
    app: productcatalogservice
  ports:
  - name: grpc
    port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
