apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
spec:
  type: ClusterIP
  selector:
    app: recommendationservice
  ports:
  - name: grpc
    port:  {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
