---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
spec:
  type: ClusterIP
  selector:
    app: checkoutservice
  ports:
  - name: grpc
    port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
