apiVersion: v1
kind: Service
metadata:
  name: paymentservice
spec:
  type: ClusterIP
  selector:
    app: paymentservice
  ports:
  - name: grpc
    port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
