{
 "title": "Frontend UI Service",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "Frontend latency (95 percentile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(opencensus_io_http_server_latency_bucket{job=~\".*-endpoints\",kubernetes_namespace=~\"$namespace\"}[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Frontend request count by method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(opencensus_io_http_server_request_count_by_method{app=\"frontend\",job=~\".*-endpoints\",kubernetes_namespace=~\"$namespace\"}[1m])"
    }
   ]
  },
  {
   "title": "Rate response count by status 404 or 500",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(opencensus_io_http_server_response_count_by_status_code{app=\"frontend\",job=~\".*-endpoints\",kubernetes_namespace=~\"$namespace\",http_status=~\"^[45].*\"}[1m])"
    }
   ]
  },
  {
   "title": "Rate response count by status 200 or 302",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(opencensus_io_http_server_response_count_by_status_code{app=\"frontend\",job=~\".*-endpoints\",kubernetes_namespace=~\"$namespace\",http_status=~\"200|302\"}[1m])"
    }
   ]
  },
  {
   "title": "Response bytes count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(opencensus_io_http_server_response_bytes_count{app=\"frontend\",job=~\".*-endpoints\",kubernetes_namespace=~\"$namespace\"}[1m])"
    }
   ]
  },
  {
   "title": "Request bytes count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(opencensus_io_http_server_request_bytes_count{app=\"frontend\",job=~\".*-endpoints\",kubernetes_namespace=~\"$namespace\"}[1m])"
    }
   ]
  }
 ]
}