---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - name: http
    port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
  - name: metrics
    port: 9090
    targetPort: 9090
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: frontend-external
# spec:
#   type: LoadBalancer
#   selector:
#     app: frontend
#   ports:
#   - name: http
#     port: {{ .Values.service.externalPort }}
#     targetPort: {{ .Values.service.internalPort }}
