---
apiVersion: v1
kind: Service
metadata:
  name: adservice
spec:
  type: ClusterIP
  selector:
    app: adservice
  ports:
  - name: grpc
    port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
  - name: metrics
    port: 9090
    targetPort: 9090
