image: devth/helm

stages:
  - test
  - staging
  - production

variables:
#    IMAGE: ${CI_REGISTRY_IMAGE}/web:${CI_COMMIT_REF_SLUG}
#    GKE_SERVICE_ACCOUNT: base64-encoded-json-service-account-file-from-gke
    GKE_CLUSTER_NAME: my-gke-cluster
    GKE_ZONE: us-central1-c
    GKE_PROJECT: notional-portal-276509
#    URL_REVIEW: ${CI_COMMIT_REF_SLUG}.your.domain.com
#    URL_PRODUCTION: your.domain.com

test:
  stage: test
  script:
    - exit 0
  only:
    - triggers
    - branches

staging:
  stage: staging
  variables:
    KUBE_NAMESPACE: staging
  environment:
    name: staging
    url: http://staging.homembr.ru
  script:
     - mkdir -p /etc/deploy
     - echo ${GKE_SERVICE_ACCOUNT} | base64 -d > /etc/deploy/sa.json
     - gcloud auth activate-service-account --key-file /etc/deploy/sa.json --project=${GKE_PROJECT}
     - gcloud container clusters get-credentials ${GKE_CLUSTER_NAME} --zone ${GKE_ZONE} --project ${GKE_PROJECT}
#     -  helm init --service-account tiller --wait --upgrade
#     - init_helm
     - helm ls
     - export track="${1-stable}"
     - >
      if [[ "$track" != "stable" ]]; then
        name="$name-$track"
      fi
     - export
     - echo name $name
     - kubectl describe namespace "$KUBE_NAMESPACE" || kubectl create namespace "$KUBE_NAMESPACE"
#     - git clone https://gitlab.homembr.ru/$CI_PROJECT_NAMESPACE/shop-deploy.git
     - git clone "$CI_REPOSITORY_URL"
     - >
      helm upgrade \
        --install \
        --wait \
        --namespace="$KUBE_NAMESPACE" \
        staging \
        shop-deploy/
  when: manual
  only:
    refs:
      - master
    kubernetes: active

production:
  stage: production
  variables:
    KUBE_NAMESPACE: production
  environment:
    name: production
    url: http://production.homembr.ru
  script:
     - mkdir -p /etc/deploy
     - echo ${GKE_SERVICE_ACCOUNT} | base64 -d > /etc/deploy/sa.json
     - gcloud auth activate-service-account --key-file /etc/deploy/sa.json --project=${GKE_PROJECT}
     - gcloud container clusters get-credentials ${GKE_CLUSTER_NAME} --zone ${GKE_ZONE} --project ${GKE_PROJECT}
#     -  helm init --service-account tiller --wait --upgrade
#     - init_helm
     - helm ls
     - export track="${1-stable}"
     - >
      if [[ "$track" != "stable" ]]; then
        name="$name-$track"
      fi
     - kubectl describe namespace "$KUBE_NAMESPACE" || kubectl create namespace "$KUBE_NAMESPACE"
#     - git clone https://gitlab.homembr.ru/$CI_PROJECT_NAMESPACE/shop-deploy.git
     - git clone "$CI_REPOSITORY_URL"
     - >
      helm upgrade \
        --install \
        --wait \
        --namespace="$KUBE_NAMESPACE" \
        production \
        shop-deploy/
  when: manual
  only:
    refs:
      - master
    kubernetes: active
