repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-yaml

- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.0.0
  hooks:
  - id: markdownlint

- repo: https://github.com/kintoandar/pre-commit
  rev: v2.1.0
  hooks:
  - id: prometheus_check_rules
  - id: prometheus_check_config
