apiVersion: v1
kind: Service
metadata:
  name: shippingservice
spec:
  type: ClusterIP
  selector:
    app: shippingservice
#    app: {{ template "shippingservice.fullname" . }}

  ports:
  - name: grpc
    port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
